// Dev-only: drive the Node tab: output replay, heartbeat, stop, health, backup, restore, old image.
const electron = require('electron');
const { app, BrowserWindow } = electron;
const http = require('http'), fs = require('fs'), path = require('path'), os = require('os');
app.commandLine.appendSwitch('no-sandbox'); app.commandLine.appendSwitch('disable-gpu');
const SHIM = fs.mkdtempSync(path.join(os.tmpdir(), 'sxm-')); process.env.SHIM_DIR = SHIM;
process.env.SAFEX_DOCKER_BIN = path.join(__dirname, 'fake-docker.sh');
app.setPath('userData', fs.mkdtempSync(path.join(os.tmpdir(), 'sxmu-')));
const set = (f, v) => v === null ? fs.rmSync(path.join(SHIM, f), { force: true }) : fs.writeFileSync(path.join(SHIM, f), v);
set('engine', 'ok'); set('image', 'x'); set('container', 'running'); set('volumes', 'safex-node-data\n'); set('mountname', 'safex-node-data');
electron.dialog.showMessageBox = async () => ({ response: 1 });   // "yes, restore"
http.createServer((q, r) => r.end(JSON.stringify({ height: 2097365, target_height: 2097364, outgoing_connections_count: 8, incoming_connections_count: 2, difficulty: 27960000, target: 120 }))).listen(17402, '127.0.0.1');
require('../src/main.js');
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
app.whenReady().then(async () => {
  const w = BrowserWindow.getAllWindows()[0]; const wc = w.webContents; const OUT = process.env.SHOT_DIR;
  const js = (c) => wc.executeJavaScript(c);
  const snap = async (n) => fs.writeFileSync(path.join(OUT, n), (await wc.capturePage()).toPNG());
  const btns = () => js(`['mHealth','mBackup','mRestore','mRebuild'].map(i=>document.getElementById(i).textContent+(document.getElementById(i).disabled?'(off)':'(on)')).join('  ')`);
  const info = () => js(`document.getElementById('maintInfo').textContent`);
  const result = () => js(`(()=>{const e=document.getElementById('maintResult');return e.hidden?'(none)':e.className+': '+e.textContent})()`);
  const outLines = () => js(`[...document.querySelectorAll('#nLog div')].map(d=>d.textContent)`);
  await wait(3000);
  await js(`document.getElementById('tabBtnNode').click()`); await wait(2500);
  console.log('1. node running');
  console.log('   maintenance:', await info()); console.log('   buttons:    ', await btns());
  const ol = await outLines();
  console.log('   output has replayed node lines:', ol.some((l) => /Synced 1500000/.test(l)), '| placeholder shown:', ol.some((l) => /Waiting for node output/.test(l)));
  await wait(2500);
  console.log('   heartbeat status line present:', (await outLines()).some((l) => /^\[status\] block 2,097,365 · 10 peers · synced/.test(l)));
  console.log('2. stop the node');
  await js(`document.getElementById('nodeBtn').click()`); await wait(7500);
  console.log('   maintenance:', await info()); console.log('   buttons:    ', await btns());
  console.log('3. health check'); await js(`document.getElementById('mHealth').click()`); await wait(4000);
  console.log('   result:', await result());
  console.log('4. backup'); await js(`document.getElementById('mBackup').click()`); await wait(4000);
  console.log('   result:', await result()); console.log('   maintenance:', await info());
  await snap('m1-backup.png');
  console.log('5. restore (confirm stubbed)'); await js(`document.getElementById('mRestore').click()`); await wait(4000);
  console.log('   result:', await result());
  console.log('6. damaged chain'); set('summary', 'SUMMARY status=DAMAGED blocks=2097365 readable=1098136 missing=0 errors=78 first_bad=1097930');
  await js(`document.getElementById('mHealth').click()`); await wait(4000); console.log('   result:', await result()); set('summary', null);
  console.log('7. old image without the health tool'); set('noscript', 'x');
  await js(`document.getElementById('mHealth').click()`); await wait(4000); console.log('   result:', await result());
  await js(`document.getElementById('mRebuild').click()`); await wait(6000); set('noscript', null);
  console.log('   rebuild ran:', (await outLines()).some((l) => /Node image rebuilt/.test(l)));
  await snap('m2-final.png');
  app.exit(0);
});
