'use strict';
const assert = require('assert');
const { build, MAX_SERIES } = require('../src/core/rigchart');
const fake = (pts) => ({ series: (w, s) => { const n = Math.ceil(w / s); const a = new Array(n).fill(null); for (const [i, v] of Object.entries(pts)) a[+i < 0 ? n + +i : +i] = v; return a; } });
let r = build('1h', [{ id: 'a', name: 'A', log: fake({ 10: 100, 11: 100, 14: 100 }) }, { id: 'b', name: 'B', log: fake({}) }], 1e6);
assert.strictEqual(r.series.length, 1, 'rig with no data is dropped');
assert.strictEqual(r.series[0].points[5], null, 'no line before first sample');
assert.strictEqual(r.series[0].points[12], 0, 'gap after first sample is a dip');
assert.strictEqual(r.step, 60); assert.strictEqual(r.total.length, 60);
r = build('24h', [{ id: 'a', name: 'A', log: fake({ 0: 50, 1: 50 }) }, { id: 'b', name: 'B', log: fake({ 1: 25 }) }], 1e6);
assert.deepStrictEqual(r.total.slice(0, 3), [50, 75, 0]);
assert.strictEqual(r.series[1].points[0], null);
const many = Array.from({ length: 11 }, (_, i) => ({ id: 'r' + i, name: 'R' + i, log: fake({ 0: 10 + i }) }));
r = build('7d', many, 1e6);
assert.strictEqual(r.series.length, MAX_SERIES); assert.strictEqual(r.series[MAX_SERIES - 1].id, 'other');
assert.strictEqual(r.total[0], many.reduce((a, _, i) => a + 10 + i, 0));
assert.strictEqual(build('bogus', [], 1e6).step, 600);
console.log('rigchart tests passed');
{
  const { BlockLog } = require('../src/core/blocklog'); const os = require('os'), fs = require('fs'), path = require('path');
  const f = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'bl-')), 'b.json'); const b = new BlockLog(f);
  assert.strictEqual(b.note('a', 'A', 0, true, 1000), 0, 'first look only sets the baseline');
  assert.strictEqual(b.note('a', 'A', 1, true, 1060), 1); assert.strictEqual(b.note('a', 'A', 1, true, 1120), 0);
  assert.strictEqual(b.note('a', 'A', 0, true, 1180), 0, 'restart resets, no event');
  assert.strictEqual(b.note('a', 'A', 1, false, 1240), 0, 'pool mode never records');
  assert.strictEqual(b.note('a', 'A', 3, true, 1300), 2);
  assert.strictEqual(new BlockLog(f).events.length, 3, 'persisted');
  const fk = (pts) => ({ series: (w, s) => { const a = new Array(Math.ceil(w / s)).fill(null); for (const i in pts) a[i] = pts[i]; return a; } });
  const r = build('1h', [{ id: 'a', name: 'A', log: fk({ 10: 5, 11: 5 }) }], 10000, [{ t: 10000 - 3600 + 60 * 10 + 5, id: 'a', name: 'A' }, { t: 5, id: 'a', name: 'A' }, { t: 9990, id: 'gone', name: 'G' }]);
  assert.strictEqual(r.blocks.length, 2, 'out-of-range event dropped'); assert.strictEqual(r.blocks[0].i, 10); assert.strictEqual(r.blocks[1].id, 'other');
  console.log('blocklog tests passed');
}
